### ISSUE TITLE
rtm

### ISSUE THREAD

**Issue by tianwen220** [YulangWu/CNN-RWI#1]
When I use pysit to run to rtm, the direct wave and full wave fields do not match, because the nstep calculated by pysit is inconsistent

**Comment by tianwen220** [comment]
This problem has been solved. Thank you

**Comment by Geophysics-Liu** [comment]
> When I use pysit to run to rtm, the direct wave and full wave fields do not match, because the nstep calculated by pysit is inconsistent

I also have this problem. May I ask how you solve it? Thanks.

**Comment by Geophysics-Liu** [comment]
> > When I use pysit to run to rtm, the direct wave and full wave fields do not match, because the nstep calculated by pysit is inconsistent
> 
> I also have this problem. May I ask how you solve it? Thanks.

given_models0/true0vp.dat 0
Generating training data without direct wave...
/home/yanhua/miniconda3/envs/myenv/lib/python3.7/site-packages/pysit-1.0.1-py3.7-linux-x86_64.egg/pysit/solvers/wavefield_vector.py:143: RuntimeWarning: invalid value encountered in multiply
  self.data *= rhs
Traceback (most recent call last):
  File "RTM.py", line 313, in <module>
    shots_scalar[num_shot].receivers._data = source_wavefields['simdata'] - Ddata
ValueError: operands could not be broadcast together with shapes (2098,256) (670,256)

**Comment by AndyJulie2008** [comment]
Please refer to the readme.txt for the instruction to fix this problem. Thanks.
